### ISSUE TITLE
なんかdepoloymentがコケてる

### ISSUE THREAD

**Issue by yanorei32** [gnknzm/gnknzm.net#133]
関連してそうなもの

Renovateによる自動更新
upload-pages-artifact: https://github.com/gnknzm/gnknzm.net/commit/8db6cef7bea58574a39d23f562bd4023e50f60ea
deploy-pages: https://github.com/gnknzm/gnknzm.net/commit/c5d34ab7ac0854cf85858fe9437d6e57dc77743e

@Ry0taK によるRegression発見
https://github.com/actions/deploy-pages/commit/b12897a760d97ad2a3315379d85b4b730c3d4b43

deploy-pagesのRegression
https://github.com/actions/deploy-pages/issues/284

**Comment by Ry0taK** [comment]
actions/deploy-pagesの4.0.2で治った

https://github.com/gnknzm/gnknzm.net/actions/runs/7357025936/job/20027991760
